# & = Color Code
# {user} = Banned user name
# {line} = Bottom line
# {admin} = Admin name

# Settings
Ban-Broadcast: true # true or false



# Messages
Prefix: "&l&6BAN&r > "
No-Permission-Message: "&7You have not permission!"
Ban-Successfully-Message: "&7{user} has been successfully banned!"
Ban-Broadcast-Message: "&6{user} &7Banned by &6{admin}!"
User-Not-Found-Message: "&7{user} not found!"
Unban-Successfully-Message: "&7{user} has been successfully unban!"
Player-Same-User-Message: "&7You can't ban yourself!"
Non-Numeric-Day-Message: "&7Enter a numeric value!"